[theme]
# Couleur principale (widgets) en rouge vif
primaryColor="#FF0000"

# Couleur de FOND en jaune vif
backgroundColor="#FFFF00"

# Couleur de la sidebar
secondaryBackgroundColor="#F0F2F6"

# Couleur du texte en noir
textColor="#000000"
font="sans serif"
